import { createContext, useContext, useState, type ReactNode } from "react";

type Language = "pt" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, variables?: Record<string, string | number>) => string;
}

const translations: Record<Language, Record<string, string>> = {
  pt: {
    // Navegação da Barra Lateral
    "nav.dashboard": "Dashboard",
    "nav.myPOs": "Minhas solicitações",
    "nav.newPO": "Nova PO",
    "nav.approvals": "Aprovações",
    "nav.legal": "Legal/Contratos",
    "nav.registrations": "Cadastros",
    "nav.users": "Usuários",
    "nav.settings": "Configurações",
    "nav.main": "Principal",
    "nav.collapse": "Recolher",
    "nav.logout": "Sair",

    // Comum
    "common.erp": "ERP Financeiro",
    "common.add": "Adicionar",
    "common.all": "Todos",
    "common.edit": "Editar",
    "common.search": "Buscar...",
    "common.searchPlaceholder": "Buscar POs, fornecedores...",
    "common.notifications": "Notificações",
    "common.markAllRead": "Marcar todas como lidas",
    "common.viewAll": "Ver todas",
    "common.profile": "Perfil",
    "common.preferences": "Preferências",
    "common.help": "Ajuda",
    "common.myAccount": "Minha Conta",
    "common.approve": "Aprovar",
    "common.reject": "Rejeitar",
    "common.return": "Devolver",
    "common.save": "Salvar",
    "common.cancel": "Cancelar",
    "common.confirm": "Confirmar",
    "common.actions": "Ações",
    "common.status": "Status",
    "common.date": "Data",
    "common.value": "Valor",
    "common.supplier": "Fornecedor",
    "common.requester": "Solicitante",
    "common.details": "Detalhes",
    "common.view": "Ver",
    "common.home": "Home",
    "common.filters": "Filtros",
    "common.allStatus": "Todos os status",
    "common.allSteps": "Todas as etapas",
    "common.showing": "Exibindo",
    "common.of": "de",
    "common.exportPDF": "Exportar PDF",
    "common.back": "Voltar",
    "common.backToList": "Voltar para lista",
    "common.today": "Hoje",
    "common.yesterday": "Ontem",
    "common.daysAgo": "dias atrás",
    "common.approved": "Homologado",
    "common.notApproved": "Não homologado",

    //Tipos de PO
    "poType.title": "Tipo de PO",
    "poType.produtos_servicos": "Produtos e Serviços",
    "poType.reembolso": "Reembolso",
    "poType.selectType": "Selecione o Tipo de PO",

    // Painel
    "dashboard.title": "Dashboard",
    "dashboard.subtitle": "Visão geral das Purchase Orders",
    "dashboard.totalPOs": "Total de POs",
    "dashboard.pendingApproval": "Aguardando Aprovação",
    "dashboard.approved": "Aprovadas",
    "dashboard.rejected": "Reprovadas",
    "dashboard.vsLastMonth": "vs mês anterior",
    "dashboard.urgentPending": "PO(s) urgente(s) pendente(s)",
    "dashboard.urgentMessage":
      "Existem POs marcadas como urgentes aguardando ação.",
    "dashboard.recentPOs": "POs Recentes",
    "dashboard.viewAll": "Ver todas",

    // Lista de POs
    "poList.title": "Minhas solicitações",
    "poList.subtitle": "Gerencie suas Purchase Orders",
    "poList.newPO": "Nova PO",
    "poList.searchPlaceholder": "Buscar por número, beneficiário ou fornecedor",

    // Cabeçalhos de Tabela
    "table.number": "Número",
    "table.title": "Beneficiário/Fornecedor",
    "table.status": "Status",
    "table.step": "Etapa",
    "table.value": "Valor",
    "table.department": "Departamento",
    "table.createdAt": "Criada em",
    "table.date": "Data",
    "table.requester": "Solicitante",

    // Status
    "status.rascunho": "Rascunho",
    "status.aguardando_aprovacao": "Aguardando Aprovação",
    "status.aprovada": "Aprovada",
    "status.reprovada": "Reprovada",
    "status.finalizada": "Finalizada",
    "status.cancelada": "Cancelada",

    // Etapas
    "step.rascunho": "Rascunho",
    "step.aguardando_aprovacao": "Aguardando Aprovação",
    "step.aguardando_contrato": "Aguardando Contrato",
    "step.realizando_pagamentos": "Realizando Pagamentos",
    "step.reprovada": "Reprovada",
    "step.baixada": "Baixada",

    // Página Nova PO
    "newPO.title": "Nova PO",
    "newPO.subtitle": "Preencha os dados para criar uma nova ordem de compra",
    "newPO.poData": "Dados da PO",
    "newPO.poSubtype": "Tipo de PO",
    "newPO.selectSubtype": "Selecione o subtipo",
    "newPO.subtypeProduct": "Produto",
    "newPO.subtypeService": "Serviço",
    "newPO.subtypeBoth": "Produtos e Serviços",
    "newPO.requester": "Solicitante",
    "newPO.beneficiary": "Beneficiário",
    "newPO.selectBeneficiary": "Selecione o beneficiário",
    "newPO.currency": "Moeda",
    "newPO.selectCurrency": "Selecione a moeda",
    "newPO.totalValue": "Valor Total",
    "newPO.totalValuePlaceholder": "0,00",
    "newPO.hasGrossUp": "Possui Gross Up?",
    "newPO.deog": "DE/OG",
    "newPO.selectDeog": "Selecione DE/OG",
    "newPO.icApproved": "Aprovado pelo IC?",
    "newPO.searchBy": "Buscar por:",
    "newPO.cpfCnpj": "CPF/CNPJ",
    "newPO.companyOrTradeName": "Razão Social / Nome Fantasia",
    "newPO.searchTaxId": "Buscar por CPF/CNPJ...",
    "newPO.searchCompanyName": "Buscar por razão social...",
    "newPO.searchTradeName": "Buscar por nome fantasia...",
    "newPO.noSupplierFound": "Nenhum fornecedor encontrado",
    "newPO.supplierNotApprovedWarning": "Fornecedor não homologado",
    "newPO.supplierNotApprovedDescription":
      "Este fornecedor não passou pelo background check. Você pode salvá-lo como rascunho, mas não poderá enviar para aprovação.",
    "newPO.supplierNotApprovedTitle": "Fornecedor não homologado",
    "newPO.supplierNotApprovedAlert":
      "Apenas fornecedores que passaram pelo background check podem ser utilizados em POs de serviço. Você pode salvar como rascunho, mas não poderá enviar para aprovação até que o fornecedor seja homologado.",
    "newPO.bank": "Banco",
    "newPO.bankPlaceholder": "Nome do banco",
    "newPO.agency": "Agência",
    "newPO.agencyPlaceholder": "Número da agência",
    "newPO.account": "Conta",
    "newPO.accountPlaceholder": "Número da conta",
    "newPO.boletoBarcode": "Código de Barras",
    "newPO.boletoBarcodePlaceholder": "Digite o código de barras do boleto",
    "newPO.boletoAttachment": "Anexar Boleto",
    "newPO.attachBoleto": "Anexar Boleto",
    "newPO.boletoAttached": "Boleto anexado com sucesso",
    "newPO.selectCCAndGL": "Selecione CC e Conta",
    "newPO.exceedsBalance": "Excede o saldo",
    "newPO.allocationExceedsTotal":
      "A soma dos valores de rateio excede o valor total da PO. Ajuste os valores para prosseguir.",
    "newPO.amountExceedsBalance": "Valor excede o saldo disponível",
    "newPO.amountExceedsBalanceDescription":
      "O valor informado é superior ao saldo disponível para este centro de custo.",
    "newPO.select": "Selecione",
    "newPO.companyName": "Razão Social",
    "newPO.tradeName": "Nome Fantasia",
    "newPO.registerSupplier": "Cadastrar Fornecedor",
    "newPO.paymentMethod": "Forma de Pagamento",
    "newPO.selectPaymentMethod": "Selecione a forma de pagamento",
    "newPO.paymentCondition": "Condição de Pagamento",
    "newPO.paymentDay": "Dia de Pagamento",
    "newPO.outsideWindow": "Fora da janela de pagamento?",
    "newPO.outsideWindowDescription":
      "Selecione se o pagamento precisar ser feito em uma data diferente das opções acima",
    "newPO.costCenters": "Centros de Custo",
    "newPO.addCostCenter": "Adicionar Centro de Custo",
    "newPO.costCenter": "Centro de Custo",
    "newPO.selectCostCenter": "Selecione o centro de custo",
    "newPO.accountCode": "Conta Contábil",
    "newPO.selectAccountCode": "Selecione a conta contábil",
    "newPO.company": "Empresa",
    "newPO.balance": "Saldo",
    "newPO.amount": "Valor",
    "newPO.amountPlaceholder": "0,00",
    "newPO.percentage": "Percentual",
    "newPO.remove": "Remover",
    "newPO.allocationSummary": "Resumo da Alocação",
    "newPO.totalAmount": "Valor Total",
    "newPO.allocated": "Alocado",
    "newPO.remaining": "Restante",
    "newPO.description": "Descrição",
    "newPO.descriptionPlaceholder": "Descreva o objetivo da PO",
    "newPO.approvalFlow": "Fluxo de Aprovação",
    "newPO.creator": "Criador",
    "newPO.functionalApprover": "Aprovador Funcional",
    "newPO.seniorApprover": "Aprovador Sênior",
    "newPO.saveDraft": "Salvar Rascunho",
    "newPO.submitApproval": "Enviar para Aprovação",
    "newPO.savedDraft": "PO salva como rascunho",
    "newPO.sentApproval": "PO enviada para aprovação",
    "newPO.expenseNature": "Natureza da Despesa",
    "newPO.selectExpenseNature": "Selecione a natureza",
    "newPO.dealExpense": "Deal Expense",
    "newPO.ongoing": "Ongoing",
    "newPO.customPaymentDay": "Dia do pagamento",
    "newPO.schaduledPaymentDays": "Pagamento será no próximo mês: ",
    "newPO.paymentJustification": "Justificativa",
    "newPO.tesasuryApprovalWarning": "Aprovação da Tesouraria necessária",
    "newPO.paymentJustificationPlaceholder":
      "Explique o motivo do pagamento fora da janela...",
    "newPO.treasuryApprovalWarning":
      "Pagamentos fora da janela de pagamento requerem aprovação adicional da Tesouraria.",
    "newPO.paymentNextMonthWarning.attention": "Atenção:",
    "newPO.paymentNextMonthWarning.message":
      "Como faltam menos de {{minDays}} dias úteis, o pagamento será provisionado para {{date}} (mês seguinte). As POs devem ser criadas com pelo menos {{minDays}} dias de antecedência.",
    "newPO.lastBusinessDay": "Último dia útil do mês",
    "newPO.paymentFrequency": "Frequência do Pagamento",
    "newPO.frequencySingle": "Único",
    "newPO.frequencyInstallments": "Parcelado",
    "newPO.frequencyRecurring": "Recorrente",
    "newPO.numberOfInstallments": "Número de Parcelas",
    "newPO.recurringMessage":
      "Serão provisionadas 18 parcelas. Novas parcelas serão criadas automaticamente até o fim do contrato.",
    "newPO.allocation": "Rateio por empresa",
    "newPO.boletoInfoMessage":
      "O boleto será inserido no detalhamento da PO após a aprovação.",
    "newPO.requiredApprovers": "Aprovadores Necessários",
    "newPO.functionalApprovers": "Aprovadores Funcionais",
    "newPO.seniorApprovers": "Aprovadores Sênior",
    "newPO.selectFunctionalApprover": "Selecionar Aprovador Funcional",
    "newPO.selectSeniorApprover": "Selecionar Aprovador Sênior",
    "newPO.selectApprover": "Selecione um aprovador",
    "newPO.availableFunctionalApprovers": "Aprovadores Funcionais Disponíveis",
    "newPO.availableSeniorApprovers": "Aprovadores Sênior Disponíveis",
    "newPO.seniorApprovalRequired":
      "Aprovação de Sênior é obrigatória para POs com valor superior a {{minValue}}.",

    //Tipos de Método de Pagamento
    "newPO.paymentMethodTypes.bankSlip": "Boleto Bancário",
    "newPO.paymentMethodTypes.bankTransfer": "Trasnferência Bancária",

    // Nova PO PortCo
    "newPOPortCo.title": "Atenção: PO para PortCo",
    "newPOPortCo.subtitle": "Não é recomendado abrir PO para PortCo.",
    "newPOPortCo.content":
      "Se for realmente necessário prosseguir, será exigida a aprovação de um Lead Partner.",
    "newPOPortCo.checkboxText": "Estou ciente e desejo continuar mesmo assim",
    "newPOPortCo.specialApproval": "Aprovação Especial para PortCo",
    "newPOPortCo.leadPartnerApproval": "Leader Partner aprovador",
    "newPOPortCo.selectLeadPartner": "Selecione o Lead Partner",
    "newPOPortCo.justification": "Justificativa",
    "newPOPortCo.justificationPlaceholder":
      "Justifique a necessidade de abrir uma PO para PortCo",

    // Página de Detalhe da PO
    "poDetail.notFound": "PO não encontrada",
    "poDetail.poNotFoundDescription":
      "Não foi possível encontrar a PO solicitada.",
    "poDetail.idNotProvided": "ID da PO não informado",
    "poDetail.loadError": "Erro ao carregar PO",
    "poDetail.loadErrorToast": "Erro ao carregar os dados da PO",
    "poDetail.generalInfo": "Informações Gerais",
    "poDetail.generalInfoDescription": "Dados básicos da Purchase Order",
    "poDetail.supplier": "Fornecedor",
    "poDetail.supplierDescription": "Dados do fornecedor",
    "poDetail.requester": "Solicitante",
    "poDetail.department": "Departamento",
    "poDetail.createdAt": "Data de Criação",
    "poDetail.lastUpdate": "Última Atualização",
    "poDetail.dueDate": "Data de Vencimento",
    "poDetail.totalValue": "Valor Total",
    "poDetail.description": "Descrição",
    "poDetail.poItems": "Itens da PO",
    "poDetail.itemDescription": "Descrição",
    "poDetail.costCenter": "Centro de Custo",
    "poDetail.quantity": "Qtd",
    "poDetail.unitPrice": "Valor Unit.",
    "poDetail.total": "Total",
    "poDetail.subtotal": "Subtotal",
    "poDetail.taxes": "Impostos",
    "poDetail.attachments": "Anexos",
    "poDetail.approvalWorkflow": "Workflow de Aprovação",
    "poDetail.levelOf": "Nível {current} de {total}",
    "poDetail.actionHistory": "Histórico de Ações",
    "poDetail.noActions": "Nenhuma ação registrada ainda",
    "poDetail.approved": "aprovou",
    "poDetail.rejected": "rejeitou",
    "poDetail.returned": "devolveu",
    "poDetail.export": "Exportar",
    "poDetail.print": "Imprimir",
    "poDetail.exportInDevelopment": "Exportar em desenvolvimento",
    "poDetail.printInDevelopment": "Imprimir em desenvolvimento",
    "poDetail.international": "Internacional",
    "poDetail.externalId": "ID Externo",
    "poDetail.poType": "Tipo de PO",
    "poDetail.expenseNature": "Natureza da Despesa",
    "poDetail.dealExpense": "Deal Expense",
    "poDetail.ongoing": "Ongoing",
    "poDetail.beneficiary": "Beneficiário",
    "poDetail.fundGP": "Fundo GP",
    "poDetail.portCo": "PortCo",
    "poDetail.icApproval": "Aprovação IC",
    "poDetail.yes": "Sim",
    "poDetail.no": "Não",
    "poDetail.observations": "Observações",
    "poDetail.legalName": "Razão Social",
    "poDetail.tradeName": "Nome Fantasia",
    "poDetail.taxId": "CNPJ/Tax ID",
    "poDetail.companyType": "Tipo de Empresa",
    "poDetail.email": "Email",
    "poDetail.address": "Endereço",
    "poDetail.payment": "Pagamento",
    "poDetail.paymentDescription": "Condições e método de pagamento",
    "poDetail.paymentCondition": "Condição de Pagamento",
    "poDetail.numberOfInstallments": "Número de Parcelas",
    "poDetail.installments": "Parcelas",
    "poDetail.currency": "Moeda",
    "poDetail.scope": "Escopo",
    "poDetail.national": "Nacional",
    "poDetail.exterior": "Exterior",
    "poDetail.paymentWindow": "Janela de Pagamento",
    "poDetail.days": "dias",
    "poDetail.grossUp": "Gross Up",
    "poDetail.outsidePaymentWindow": "Fora da Janela de Pagamento",
    "poDetail.justification": "Justificativa",
    "poDetail.accountingAllocation": "Rateio Contábil",
    "poDetail.accountingAllocationDescription":
      "Distribuição por centro de custo e conta contábil",
    "poDetail.glAccount": "Conta Contábil",
    "poDetail.company": "Empresa",
    "poDetail.value": "Valor",
    "poDetail.installmentsAttachments": "Parcelas e Anexos",
    "poDetail.installmentsAttachmentsDescription":
      "Detalhamento das parcelas com boletos e notas fiscais",
    "poDetail.poHistory": "Histórico da PO",
    "poDetail.detailsObservations": "Detalhamento / Observações",
    "poDetail.currentStatus": "Status Atual",
    "poDetail.currentStep": "Etapa Atual",
    "poDetail.stepDetails": "Detalhamento das Etapas",
    "poDetail.noEventsRecorded": "Nenhum evento registrado ainda.",
    "poDetail.at": "às",
    "poDetail.paymentSingle": "Pagamento Único",
    "poDetail.paymentInstallments": "Parcelado",
    "poDetail.paymentRecurring": "Recorrente",
    "poDetail.typeProductsServices": "Produtos/Serviços",
    "poDetail.typeReimbursement": "Reembolso",
    "poDetail.subtypeProduct": "Produto",
    "poDetail.subtypeService": "Serviço",
    "poDetail.subtypeDefault": "Padrão",
    "poDetail.stepDraft": "Rascunho",
    "poDetail.stepAwaitingApproval": "Aguardando Aprovação",
    "poDetail.stepAwaitingContract": "Aguardando Contrato",
    "poDetail.stepProcessingPayments": "Realizando Pagamentos",
    "poDetail.stepRejected": "Reprovada",
    "poDetail.stepClosed": "Baixada",

    // Tipos de Evento de Histórico
    "history.noEvents": "Nenhum evento registrado",
    "history.eventType.created": "Criada",
    "history.eventType.submitted": "Enviada para aprovação",
    "history.eventType.approved": "Aprovada",
    "history.eventType.rejected": "Reprovada",
    "history.eventType.status_changed": "Status alterado",
    "history.eventType.step_changed": "Etapa alterada",
    "history.eventType.edited": "Editada",
    "history.eventType.comment_added": "Comentário adicionado",
    "history.eventType.attachment_added": "Anexo adicionado",
    "history.eventType.boleto_added": "Boleto adicionado",
    "history.eventType.invoice_added": "Nota fiscal adicionada",
    "history.eventType.payment_scheduled": "Pagamento agendado",
    "history.eventType.payment_completed": "Pagamento realizado",
    "history.eventType.finalized": "Finalizada",

    // Títulos de Eventos de Histórico (dinâmico)
    "history.title.poCreated": "PO criada",
    "history.title.sentForApproval": "Enviada para aprovação",
    "history.title.approvedBy": "Aprovado por",
    "history.title.rejectedBy": "Rejeitado por",
    "history.title.statusChangedTo": "Status alterado para",
    "history.title.stepChangedTo": "Etapa alterada para",
    "history.title.poFinalized": "PO Finalizada",

    // Tabela de Alocação de Parcelas
    "installment.filters": "Filtros:",
    "installment.allCompanies": "Todas as empresas",
    "installment.allInstallments": "Todas as parcelas",
    "installment.installment": "Parcela",
    "installment.installmentN": "Parcela",
    "installment.dueDate": "Vencimento",
    "installment.value": "Valor",
    "installment.status": "Status",
    "installment.paymentData": "Dados Pgto",
    "installment.attachments": "Anexos",
    "installment.actions": "Ações",
    "installment.noAttachment": "Nenhum anexo",
    "installment.boleto": "Boleto",
    "installment.invoice": "Nota Fiscal",
    "installment.attach": "Anexar",
    "installment.uploadedOn": "Enviado em",
    "installment.provisioned": "Provisionado",
    "installment.scheduled": "Agendado",
    "installment.paid": "Pago",
    "installment.provisionedDesc": "Aguardando anexo ou confirmação",
    "installment.scheduledDesc": "Anexo inserido, aguardando pagamento",
    "installment.paidDesc": "Pagamento realizado",
    "installment.confirmData": "Confirmar dados",
    "installment.confirmed": "Confirmado",
    "installment.paymentDataTitle": "Dados de Pagamento",
    "installment.installmentSuffix": "ª Parcela",
    "installment.editPaymentData": "Edite os dados bancários para esta parcela",
    "installment.confirmPaymentData":
      "Confirme ou ajuste os dados bancários para esta parcela",
    "installment.bank": "Banco",
    "installment.bankPlaceholder": "Ex: Banco do Brasil",
    "installment.agency": "Agência",
    "installment.account": "Conta",
    "installment.editData": "Editar dados",
    "installment.adjustData": "Ajustar dados",
    "installment.saveChanges": "Salvar alterações",
    "installment.pay": "Pagar",
    "installment.attachedSuccess": "anexado com sucesso",
    "installment.attachmentRemoved": "Anexo removido",
    "installment.installmentConfirmed": "confirmada",
    "installment.paymentDataUpdated": "Dados de pagamento atualizados",
    "installment.paymentMarkedAsPaid": "Pagamento marcado como realizado",
    "installment.divergenceTitle": "Divergência no rateio:",
    "installment.divergenceDesc":
      "O total do rateio ({total}) não corresponde ao valor total da PO ({poTotal}).",
    "installment.installments": "parcela",
    "installment.installmentsPlural": "parcelas",
    "installment.paidSingular": "paga",
    "installment.paidPlural": "pagas",
    "installment.summaryByCompany": "Resumo por Empresa",
    "installment.grandTotal": "Total Geral",
    "installment.viewFile": "Visualizar arquivo",
    "installment.downloadFile": "Baixar arquivo",
    "installment.paymentinfoMessage":
      "Dados de Pagamento - {installment.installmentNumber}ª Parcela",

    // Página de Edição de PO
    "poEdit.editTitle": "Editar PO",
    "poEdit.enableEdit": "Edição habilitada",
    "poEdit.draftAlertTitle": "Rascunho",
    "poEdit.draftAlertDescription":
      "Esta PO está em modo de edição. Você pode modificar os campos e salvar suas alterações ou enviar para aprovação.",

    // Fornecedores
    "nav.suppliers": "Fornecedores",
    "suppliers.title": "Fornecedores",
    "suppliers.subtitle": "Gerencie os fornecedores cadastrados",
    "suppliers.newSupplier": "Novo Fornecedor",
    "suppliers.newSupplierDescription":
      "Preencha os dados para cadastrar um novo fornecedor",
    "suppliers.totalSuppliers": "Total de Fornecedores",
    "suppliers.activeSuppliers": "Fornecedores Ativos",
    "suppliers.inactiveSuppliers": "Fornecedores Inativos",
    "suppliers.list": "Lista de Fornecedores",
    "suppliers.searchPlaceholder":
      "Buscar por CNPJ, razão social ou nome fantasia...",
    "suppliers.noSuppliers": "Nenhum fornecedor encontrado",
    "suppliers.active": "Ativo",
    "suppliers.inactive": "Inativo",
    "suppliers.blocked": "Bloqueado",
    "suppliers.createdSuccess": "Fornecedor cadastrado com sucesso!",
    "suppliers.basicInfo": "Dados Básicos",
    "suppliers.address": "Endereço",
    "suppliers.bankInfo": "Dados Bancários",
    "suppliers.cnpj": "CNPJ",
    "suppliers.cnpjPlaceholder": "00.000.000/0001-00",
    "suppliers.companyName": "Razão Social",
    "suppliers.companyNamePlaceholder": "Nome da empresa",
    "suppliers.tradeName": "Nome Fantasia",
    "suppliers.tradeNamePlaceholder": "Nome fantasia",
    "suppliers.email": "E-mail",
    "suppliers.emailPlaceholder": "email@empresa.com",
    "suppliers.phone": "Telefone",
    "suppliers.phonePlaceholder": "(00) 00000-0000",
    "suppliers.zipCode": "CEP",
    "suppliers.zipCodePlaceholder": "00000-000",
    "suppliers.street": "Logradouro",
    "suppliers.streetPlaceholder": "Rua, Avenida, etc.",
    "suppliers.number": "Número",
    "suppliers.numberPlaceholder": "000",
    "suppliers.complement": "Complemento",
    "suppliers.complementPlaceholder": "Sala, Andar, etc.",
    "suppliers.neighborhood": "Bairro",
    "suppliers.neighborhoodPlaceholder": "Nome do bairro",
    "suppliers.city": "Cidade",
    "suppliers.cityPlaceholder": "Nome da cidade",
    "suppliers.state": "Estado",
    "suppliers.statePlaceholder": "UF",
    "suppliers.bank": "Banco",
    "suppliers.bankPlaceholder": "Nome do banco",
    "suppliers.accountType": "Tipo de Conta",
    "suppliers.selectAccountType": "Selecione o tipo",
    "suppliers.checking": "Conta Corrente",
    "suppliers.savings": "Conta Poupança",
    "suppliers.agency": "Agência",
    "suppliers.agencyPlaceholder": "0000",
    "suppliers.account": "Conta",
    "suppliers.accountPlaceholder": "00000-0",
    "suppliers.approval": "Homologação",
    "suppliers.filterByApproval": "Filtrar por homologação",
    "suppliers.approvedSuppliers": "Fornecedores Homologados",
    "suppliers.notApprovedSuppliers": "Fornecedores Não Homologados",
    "suppliers.filterByStatus": "Filtrar por status",
    "supplierDetail.notFound": "Fornecedor não encontrado",
    "supplierDetail.notFoundDescription":
      "Não foi possível encontrar o fornecedor solicitado.",
    "supplierDetail.companyInfo": "Informações da Empresa",
    "supplierDetail.contactInfo": "Informações de Contato",
    "supplierDetail.companyType": "Tipo de Empresa",
    "supplierDetail.companySize": "Porte",
    "supplierDetail.offeringType": "Tipo de Oferta",
    "supplierDetail.offeringProduct": "Produto",
    "supplierDetail.offeringService": "Serviço",
    "supplierDetail.offeringBoth": "Produtos e Serviços",
    "supplierDetail.tags": "Tags",
    "supplierDetail.primaryContact": "Contato Principal",
    "supplierDetail.contactName": "Nome",
    "supplierDetail.additionalInfo": "Informações Adicionais",
    "supplierDetail.approvalStatus": "Status de Homologação",
    "supplierDetail.approved": "Homologado",
    "supplierDetail.notApproved": "Não Homologado",
    "supplierDetail.approvedDescription":
      "Fornecedor passou pelo background check",
    "supplierDetail.notApprovedDescription":
      "Fornecedor pendente de homologação",
    "supplierDetail.approvedAt": "Homologado em",
    "supplierDetail.validUntil": "Válido até",
    "supplierDetail.quickActions": "Ações Rápidas",
    "supplierDetail.viewPOs": "Ver POs deste fornecedor",
    "supplierDetail.editSupplier": "Editar fornecedor",
    "supplierDetail.isApproved": "Fornecedor Homologado",
    "supplierDetail.sizeMEI": "MEI - Microempreendedor Individual",
    "supplierDetail.sizeME": "ME - Microempresa",
    "supplierDetail.sizeEPP": "EPP - Empresa de Pequeno Porte",
    "supplierDetail.sizeMedium": "Média Empresa",
    "supplierDetail.sizeLarge": "Grande Empresa",

    // Página de Novo Fornecedor
    "newSupplier.supplierData": "Dados do Fornecedor",
    "newSupplier.contact": "Contato",
    "newSupplier.attachments": "Anexos",

    // Barra Superior / Breadcrumbs
    "breadcrumb.purchaseOrders": "Purchase Orders",
    "breadcrumb.newPO": "Nova PO",
    "breadcrumb.approvals": "Aprovações",
    "breadcrumb.legal": "Legal/Contratos",
    "breadcrumb.registrations": "Cadastros",
    "breadcrumb.users": "Usuários",
    "breadcrumb.settings": "Configurações",

    // Notificações
    "notification.poAwaitingApproval": "PO aguardando aprovação",
    "notification.poApproved": "PO aprovada",
    "notification.contractExpiring": "Contrato vencendo",
    "notification.requiresAnalysis": "requer sua análise",
    "notification.wasApproved": "foi aprovada",
    "notification.expiresIn": "vence em",
    "notification.days": "dias",
    "notification.viewAllNotifications": "Ver todas as notificações",
  },
  en: {
    // Navegação da Barra Lateral
    "nav.dashboard": "Dashboard",
    "nav.myPOs": "My requests",
    "nav.newPO": "New PO",
    "nav.approvals": "Approvals",
    "nav.legal": "Legal/Contracts",
    "nav.registrations": "Registrations",
    "nav.users": "Users",
    "nav.settings": "Settings",
    "nav.main": "Main",
    "nav.collapse": "Collapse",
    "nav.logout": "Logout",

    // Comum
    "common.erp": "ERP Finance",
    "common.add": "Add",
    "common.all": "All",
    "common.edit": "Edit",
    "common.search": "Search...",
    "common.searchPlaceholder": "Search POs, suppliers...",
    "common.notifications": "Notifications",
    "common.markAllRead": "Mark all as read",
    "common.viewAll": "View all",
    "common.profile": "Profile",
    "common.preferences": "Preferences",
    "common.help": "Help",
    "common.myAccount": "My Account",
    "common.approve": "Approve",
    "common.reject": "Reject",
    "common.return": "Return",
    "common.showing": "Showing",
    "common.of": "of",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.confirm": "Confirm",
    "common.actions": "Actions",
    "common.status": "Status",
    "common.date": "Date",
    "common.value": "Value",
    "common.supplier": "Supplier",
    "common.requester": "Requester",
    "common.details": "Details",
    "common.view": "View",
    "common.home": "Home",
    "common.filters": "Filters",
    "common.allStatus": "All status",
    "common.allSteps": "All steps",
    "common.exportPDF": "Export PDF",
    "common.back": "Back",
    "common.backToList": "Back to list",
    "common.today": "Today",
    "common.yesterday": "Yesterday",
    "common.daysAgo": "days ago",
    "common.approved": "Approved",
    "common.notApproved": "Not Approved",

    //Tipos de PO
    "poType.title": "PO Type",
    "poType.produtos_servicos": "Products & Services",
    "poType.reembolso": "Reimbursement",
    "poType.selectType": "Select PO Type",

    // Painel
    "dashboard.title": "Dashboard",
    "dashboard.subtitle": "Purchase Orders Overview",
    "dashboard.totalPOs": "Total POs",
    "dashboard.pendingApproval": "Pending Approval",
    "dashboard.approved": "Approved",
    "dashboard.rejected": "Rejected",
    "dashboard.vsLastMonth": "vs last month",
    "dashboard.urgentPending": "urgent PO(s) pending",
    "dashboard.urgentMessage":
      "There are POs marked as urgent awaiting action.",
    "dashboard.recentPOs": "Recent POs",
    "dashboard.viewAll": "View all",

    // Lista de POs
    "poList.title": "My Requests",
    "poList.subtitle": "Manage your Purchase Orders",
    "poList.newPO": "New PO",
    "poList.searchPlaceholder": "Search by number, beneficiary or supplier",

    // Cabeçalhos de Tabela
    "table.number": "Number",
    "table.title": "Beneficiary/Supplier",
    "table.status": "Status",
    "table.step": "Step",
    "table.value": "Value",
    "table.department": "Department",
    "table.createdAt": "Created at",
    "table.date": "Date",
    "table.requester": "Requester",

    // Status
    "status.rascunho": "Draft",
    "status.aguardando_aprovacao": "Awaiting Approval",
    "status.aprovada": "Approved",
    "status.reprovada": "Rejected",
    "status.finalizada": "Finalized",
    "status.cancelada": "Canceled",
    // Etapas
    "step.rascunho": "Draft",
    "step.aguardando_aprovacao": "Awaiting Approval",
    "step.aguardando_contrato": "Awaiting Contract",
    "step.realizando_pagamentos": "Processing Payments",
    "step.reprovada": "Rejected",
    "step.baixada": "Done",

    // Página Nova PO
    "newPO.title": "New PO",
    "newPO.subtitle": "Fill in the data to create a new purchase order",
    "newPO.poData": "PO Data",
    "newPO.poSubtype": "PO Type",
    "newPO.selectSubtype": "Select subtype",
    "newPO.subtypeProduct": "Product",
    "newPO.subtypeService": "Service",
    "newPO.subtypeBoth": "Products and Services",
    "newPO.requester": "Requester",
    "newPO.beneficiary": "Beneficiary",
    "newPO.selectBeneficiary": "Select beneficiary",
    "newPO.currency": "Currency",
    "newPO.selectCurrency": "Select currency",
    "newPO.totalValue": "Total Value",
    "newPO.totalValuePlaceholder": "0.00",
    "newPO.hasGrossUp": "Has Gross Up?",
    "newPO.deog": "DE/OG",
    "newPO.selectDeog": "Select DE/OG",
    "newPO.icApproved": "IC Approved?",
    "newPO.searchBy": "Search by:",
    "newPO.cpfCnpj": "Tax ID",
    "newPO.companyOrTradeName": "Company Name / Trade Name",
    "newPO.searchTaxId": "Search by Tax ID...",
    "newPO.searchCompanyName": "Search by company name...",
    "newPO.searchTradeName": "Search by trade name...",
    "newPO.noSupplierFound": "No supplier found",
    "newPO.supplierNotApprovedWarning": "Supplier not approved",
    "newPO.schaduledPaymentDays": " Payment will be next month: ",
    "newPO.supplierNotApprovedDescription":
      "This supplier has not passed the background check. You can save as draft, but cannot submit for approval.",
    "newPO.supplierNotApprovedTitle": "Supplier not approved",
    "newPO.supplierNotApprovedAlert":
      "Only suppliers that have passed the background check can be used in service POs. You can save as draft, but cannot submit for approval until the supplier is approved.",
    "newPO.bank": "Bank",
    "newPO.bankPlaceholder": "Bank name",
    "newPO.agency": "Branch",
    "newPO.agencyPlaceholder": "Branch number",
    "newPO.account": "Account",
    "newPO.accountPlaceholder": "Account number",
    "newPO.boletoBarcode": "Barcode",
    "newPO.boletoBarcodePlaceholder": "Enter the boleto barcode",
    "newPO.boletoAttachment": "Attach Boleto",
    "newPO.attachBoleto": "Attach Boleto",
    "newPO.boletoAttached": "Boleto attached successfully",
    "newPO.selectCCAndGL": "Select CC and Account",
    "newPO.exceedsBalance": "Exceeds balance",
    "newPO.allocationExceedsTotal":
      "The sum of allocation values exceeds the PO total value. Adjust the values to proceed.",
    "newPO.amountExceedsBalance": "Amount exceeds available balance",
    "newPO.amountExceedsBalanceDescription":
      "The entered amount is greater than the available balance for this cost center.",
    "newPO.select": "Select",
    "newPO.companyName": "Company Name",
    "newPO.tradeName": "Trade Name",
    "newPO.registerSupplier": "Register Supplier",
    "newPO.paymentMethod": "Payment Method",
    "newPO.selectPaymentMethod": "Select payment method",
    "newPO.paymentCondition": "Payment Condition",
    "newPO.paymentDay": "Payment Day",
    "newPO.outsideWindow": "Outside payment window?",
    "newPO.outsideWindowDescription":
      "Select if the payment needs to be made on a date different from the options above",
    "newPO.costCenters": "Cost Centers",
    "newPO.addCostCenter": "Add Cost Center",
    "newPO.costCenter": "Cost Center",
    "newPO.selectCostCenter": "Select cost center",
    "newPO.accountCode": "Account Code",
    "newPO.selectAccountCode": "Select account code",
    "newPO.company": "Company",
    "newPO.balance": "Balance",
    "newPO.amount": "Amount",
    "newPO.amountPlaceholder": "0.00",
    "newPO.percentage": "Percentage",
    "newPO.remove": "Remove",
    "newPO.allocationSummary": "Allocation Summary",
    "newPO.totalAmount": "Total Amount",
    "newPO.allocated": "Allocated",
    "newPO.remaining": "Remaining",
    "newPO.description": "Description",
    "newPO.descriptionPlaceholder": "Describe the purpose of the PO",
    "newPO.approvalFlow": "Approval Flow",
    "newPO.creator": "Creator",
    "newPO.functionalApprover": "Functional Approver",
    "newPO.seniorApprover": "Senior Approver",
    "newPO.saveDraft": "Save Draft",
    "newPO.submitApproval": "Submit for Approval",
    "newPO.savedDraft": "PO saved as draft",
    "newPO.sentApproval": "PO sent for approval",
    "newPO.expenseNature": "Expense Nature",
    "newPO.selectExpenseNature": "Select nature",
    "newPO.paymentFrequency": "Payment Frequency",
    "newPO.frequencySingle": "Single",
    "newPO.frequencyInstallments": "Installments",
    "newPO.frequencyRecurring": "Recurring",
    "newPO.numberOfInstallments": "Number of Installments",
    "newPO.recurringMessage":
      "18 installments will be provisioned. New installments will be automatically created until the end of the contract.",
    "newPO.dealExpense": "Deal Expense",
    "newPO.ongoing": "Ongoing",
    "newPO.customPaymentDay": "Payment day",
    "newPO.paymentJustification": "Justification",
    "newPO.tesasuryApprovalWarning": " Treasury Approval Required",
    "newPO.paymentJustificationPlaceholder":
      "Explain the reason for payment outside the window...",
    "newPO.treasuryApprovalWarning":
      "Payments outside the payment window require additional Treasury approval.",
    "newPO.paymentNextMonthWarning.attention": "Attention:",
    "newPO.paymentNextMonthWarning.message":
      "As there are less than {{minDays}} business days remaining, the payment will be scheduled for {{date}} (next month). POs must be created at least {{minDays}} days in advance.",
    "newPO.lastBusinessDay": "Last business day of month",
    "newPO.allocation": "Allocation by company",
    "newPO.boletoInfoMessage":
      "The boleto will be added in the PO details after approval.",
    "newPO.requiredApprovers": "Required Approvers",
    "newPO.functionalApprovers": "Functional Approvers",
    "newPO.seniorApprovers": "Senior Approvers",
    "newPO.selectFunctionalApprover": "Select Functional Approver",
    "newPO.selectSeniorApprover": "Select Senior Approver",
    "newPO.selectApprover": "Select an approver",
    "newPO.availableFunctionalApprovers": "Available Functional Approvers",
    "newPO.availableSeniorApprovers": "Available Senior Approvers",
    "newPO.seniorApprovalRequired":
      "Senior approval is required for POs with value over {{minValue}}.",

    //Tipos de Método de Pagamento
    "newPO.paymentMethodTypes.bankSlip": "Bank Slip",
    "newPO.paymentMethodTypes.bankTransfer": "Bank Transfer",

    // Nova PO PortCo
    "newPOPortCo.title": "Attention: PO for PortCo",
    "newPOPortCo.subtitle": "It is not recommended to open a PO for PortCo.",
    "newPOPortCo.content":
      "If it is really necessary to proceed, approval from a Lead Partner will be required.",
    "newPOPortCo.checkboxText": "I am aware and wish to continue anyway",
    "newPOPortCo.specialApproval": "Special Approval for PortCo",
    "newPOPortCo.leadPartnerApproval": "Leader Partner approver",
    "newPOPortCo.selectLeadPartner": "Select Lead Partner",
    "newPOPortCo.justification": "Justification",
    "newPOPortCo.justificationPlaceholder":
      "Justify the need to open a PO for PortCo",

    // Página de Detalhe da PO
    "poDetail.notFound": "PO not found",
    "poDetail.poNotFoundDescription": "Could not find the requested PO.",
    "poDetail.idNotProvided": "PO ID not provided",
    "poDetail.loadError": "Error loading PO",
    "poDetail.loadErrorToast": "Error loading PO data",
    "poDetail.generalInfo": "General Information",
    "poDetail.generalInfoDescription": "Basic Purchase Order data",
    "poDetail.supplier": "Supplier",
    "poDetail.supplierDescription": "Supplier data",
    "poDetail.requester": "Requester",
    "poDetail.department": "Department",
    "poDetail.createdAt": "Creation Date",
    "poDetail.lastUpdate": "Last Update",
    "poDetail.dueDate": "Due Date",
    "poDetail.totalValue": "Total Value",
    "poDetail.description": "Description",
    "poDetail.poItems": "PO Items",
    "poDetail.itemDescription": "Description",
    "poDetail.installments": "Installments",
    "poDetail.costCenter": "Cost Center",
    "poDetail.quantity": "Qty",
    "poDetail.unitPrice": "Unit Price",
    "poDetail.total": "Total",
    "poDetail.subtotal": "Subtotal",
    "poDetail.taxes": "Taxes",
    "poDetail.attachments": "Attachments",
    "poDetail.approvalWorkflow": "Approval Workflow",
    "poDetail.levelOf": "Level {current} of {total}",
    "poDetail.actionHistory": "Action History",
    "poDetail.noActions": "No actions recorded yet",
    "poDetail.approved": "approved",
    "poDetail.rejected": "rejected",
    "poDetail.returned": "returned",
    "poDetail.export": "Export",
    "poDetail.print": "Print",
    "poDetail.exportInDevelopment": "Export in development",
    "poDetail.printInDevelopment": "Print in development",
    "poDetail.international": "International",
    "poDetail.externalId": "External ID",
    "poDetail.poType": "PO Type",
    "poDetail.expenseNature": "Expense Nature",
    "poDetail.dealExpense": "Deal Expense",
    "poDetail.ongoing": "Ongoing",
    "poDetail.beneficiary": "Beneficiary",
    "poDetail.fundGP": "Fund GP",
    "poDetail.portCo": "PortCo",
    "poDetail.icApproval": "IC Approval",
    "poDetail.yes": "Yes",
    "poDetail.no": "No",
    "poDetail.observations": "Observations",
    "poDetail.legalName": "Legal Name",
    "poDetail.tradeName": "Trade Name",
    "poDetail.taxId": "Tax ID",
    "poDetail.companyType": "Company Type",
    "poDetail.email": "Email",
    "poDetail.address": "Address",
    "poDetail.payment": "Payment",
    "poDetail.paymentDescription": "Payment conditions and method",
    "poDetail.paymentCondition": "Payment Condition",
    "poDetail.numberOfInstallments": "Number of Installments",
    "poDetail.currency": "Currency",
    "poDetail.scope": "Scope",
    "poDetail.national": "National",
    "poDetail.exterior": "International",
    "poDetail.paymentWindow": "Payment Window",
    "poDetail.days": "days",
    "poDetail.grossUp": "Gross Up",
    "poDetail.outsidePaymentWindow": "Outside Payment Window",
    "poDetail.justification": "Justification",
    "poDetail.accountingAllocation": "Accounting Allocation",
    "poDetail.accountingAllocationDescription":
      "Distribution by cost center and GL account",
    "poDetail.glAccount": "GL Account",
    "poDetail.company": "Company",
    "poDetail.value": "Value",
    "poDetail.installmentsAttachments": "Installments & Attachments",
    "poDetail.installmentsAttachmentsDescription":
      "Installment details with boletos and invoices",
    "poDetail.poHistory": "PO History",
    "poDetail.detailsObservations": "Details / Observations",
    "poDetail.currentStatus": "Current Status",
    "poDetail.currentStep": "Current Step",
    "poDetail.stepDetails": "Step Details",
    "poDetail.noEventsRecorded": "No events recorded yet.",
    "poDetail.at": "at",
    "poDetail.paymentSingle": "Single Payment",
    "poDetail.paymentInstallments": "Installments",
    "poDetail.paymentRecurring": "Recurring",
    "poDetail.typeProductsServices": "Products/Services",
    "poDetail.typeReimbursement": "Reimbursement",
    "poDetail.subtypeProduct": "Product",
    "poDetail.subtypeService": "Service",
    "poDetail.subtypeDefault": "Default",
    "poDetail.stepDraft": "Draft",
    "poDetail.stepAwaitingApproval": "Awaiting Approval",
    "poDetail.stepAwaitingContract": "Awaiting Contract",
    "poDetail.stepProcessingPayments": "Processing Payments",
    "poDetail.stepRejected": "Rejected",
    "poDetail.stepClosed": "Closed",

    // Tipos de Evento de Histórico
    "history.noEvents": "No events recorded",
    "history.eventType.created": "Created",
    "history.eventType.submitted": "Submitted for approval",
    "history.eventType.approved": "Approved",
    "history.eventType.rejected": "Rejected",
    "history.eventType.status_changed": "Status changed",
    "history.eventType.step_changed": "Step changed",
    "history.eventType.edited": "Edited",
    "history.eventType.comment_added": "Comment added",
    "history.eventType.attachment_added": "Attachment added",
    "history.eventType.boleto_added": "Boleto added",
    "history.eventType.invoice_added": "Invoice added",
    "history.eventType.payment_scheduled": "Payment scheduled",
    "history.eventType.payment_completed": "Payment completed",
    "history.eventType.finalized": "Finalized",

    // Títulos de Eventos de Histórico (dinâmico)
    "history.title.poCreated": "PO created",
    "history.title.sentForApproval": "Sent for approval",
    "history.title.approvedBy": "Approved by",
    "history.title.rejectedBy": "Rejected by",
    "history.title.statusChangedTo": "Status changed to",
    "history.title.stepChangedTo": "Step changed to",
    "history.title.poFinalized": "PO Finalized",

    // Tabela de Alocação de Parcelas
    "installment.filters": "Filters:",
    "installment.allCompanies": "All companies",
    "installment.allInstallments": "All installments",
    "installment.installment": "Installment",
    "installment.installmentN": "Installment",
    "installment.dueDate": "Due Date",
    "installment.value": "Value",
    "installment.status": "Status",
    "installment.paymentData": "Payment Data",
    "installment.attachments": "Attachments",
    "installment.actions": "Actions",
    "installment.noAttachment": "No attachments",
    "installment.boleto": "Boleto",
    "installment.invoice": "Invoice",
    "installment.attach": "Attach",
    "installment.uploadedOn": "Uploaded on",
    "installment.provisioned": "Provisioned",
    "installment.scheduled": "Scheduled",
    "installment.paid": "Paid",
    "installment.provisionedDesc": "Awaiting attachment or confirmation",
    "installment.scheduledDesc": "Attachment added, awaiting payment",
    "installment.paidDesc": "Payment completed",
    "installment.confirmData": "Confirm data",
    "installment.confirmed": "Confirmed",
    "installment.paymentDataTitle": "Payment Data",
    "installment.installmentSuffix": " Installment",
    "installment.editPaymentData": "Edit bank details for this installment",
    "installment.confirmPaymentData":
      "Confirm or adjust bank details for this installment",
    "installment.bank": "Bank",
    "installment.bankPlaceholder": "e.g. Bank of America",
    "installment.agency": "Branch",
    "installment.account": "Account",
    "installment.editData": "Edit data",
    "installment.adjustData": "Adjust data",
    "installment.saveChanges": "Save changes",
    "installment.pay": "Pay",
    "installment.attachedSuccess": "attached successfully",
    "installment.attachmentRemoved": "Attachment removed",
    "installment.installmentConfirmed": "confirmed",
    "installment.paymentDataUpdated": "Payment data updated",
    "installment.paymentMarkedAsPaid": "Payment marked as completed",
    "installment.divergenceTitle": "Allocation divergence:",
    "installment.divergenceDesc":
      "The allocation total ({total}) does not match the PO total ({poTotal}).",
    "installment.installments": "installment",
    "installment.installmentsPlural": "installments",
    "installment.paidSingular": "paid",
    "installment.paidPlural": "paid",
    "installment.summaryByCompany": "Summary by Company",
    "installment.grandTotal": "Grand Total",
    "installment.viewFile": "View file",
    "installment.downloadFile": "Download file",
    "installment.paymentinfoMessage":
      "Payment Data - {installment.installmentNumber}ª Installment",

    // Página de Edição de PO
    "poEdit.editTitle": "Edit PO",
    "poEdit.enableEdit": "Edit enabled",
    "poEdit.draftAlertTitle": "Draft",
    "poEdit.draftAlertDescription":
      "This PO is in edit mode. You can modify the fields and save your changes or submit for approval.",

    // Fornecedores
    "nav.suppliers": "Suppliers",
    "suppliers.title": "Suppliers",
    "suppliers.subtitle": "Manage registered suppliers",
    "suppliers.newSupplier": "New Supplier",
    "suppliers.newSupplierDescription":
      "Fill in the data to register a new supplier",
    "suppliers.totalSuppliers": "Total Suppliers",
    "suppliers.activeSuppliers": "Active Suppliers",
    "suppliers.inactiveSuppliers": "Inactive Suppliers",
    "suppliers.list": "Supplier List",
    "suppliers.searchPlaceholder":
      "Search by Tax ID, company name or trade name...",
    "suppliers.noSuppliers": "No suppliers found",
    "suppliers.active": "Active",
    "suppliers.inactive": "Inactive",
    "suppliers.blocked": "Blocked",
    "suppliers.createdSuccess": "Supplier registered successfully!",
    "suppliers.basicInfo": "Basic Info",
    "suppliers.address": "Address",
    "suppliers.bankInfo": "Bank Info",
    "suppliers.cnpj": "Tax ID",
    "suppliers.cnpjPlaceholder": "00.000.000/0001-00",
    "suppliers.companyName": "Company Name",
    "suppliers.companyNamePlaceholder": "Company name",
    "suppliers.tradeName": "Trade Name",
    "suppliers.tradeNamePlaceholder": "Trade name",
    "suppliers.email": "Email",
    "suppliers.emailPlaceholder": "email@company.com",
    "suppliers.phone": "Phone",
    "suppliers.phonePlaceholder": "(00) 00000-0000",
    "suppliers.zipCode": "ZIP Code",
    "suppliers.zipCodePlaceholder": "00000-000",
    "suppliers.street": "Street",
    "suppliers.streetPlaceholder": "Street, Avenue, etc.",
    "suppliers.number": "Number",
    "suppliers.numberPlaceholder": "000",
    "suppliers.complement": "Complement",
    "suppliers.complementPlaceholder": "Suite, Floor, etc.",
    "suppliers.neighborhood": "Neighborhood",
    "suppliers.neighborhoodPlaceholder": "Neighborhood name",
    "suppliers.city": "City",
    "suppliers.cityPlaceholder": "City name",
    "suppliers.state": "State",
    "suppliers.statePlaceholder": "ST",
    "suppliers.bank": "Bank",
    "suppliers.bankPlaceholder": "Bank name",
    "suppliers.accountType": "Account Type",
    "suppliers.selectAccountType": "Select type",
    "suppliers.checking": "Checking Account",
    "suppliers.savings": "Savings Account",
    "suppliers.agency": "Branch",
    "suppliers.agencyPlaceholder": "0000",
    "suppliers.account": "Account",
    "suppliers.accountPlaceholder": "00000-0",
    "suppliers.approval": "Approval",
    "suppliers.filterByApproval": "Filter by approval",
    "suppliers.approvedSuppliers": "Approved Suppliers",
    "suppliers.notApprovedSuppliers": "Not Approved Suppliers",
    "suppliers.filterByStatus": "Filter by status",
    "supplierDetail.notFound": "Supplier not found",
    "supplierDetail.notFoundDescription":
      "Could not find the requested supplier.",
    "supplierDetail.companyInfo": "Company Information",
    "supplierDetail.contactInfo": "Contact Information",
    "supplierDetail.companyType": "Company Type",
    "supplierDetail.companySize": "Company Size",
    "supplierDetail.offeringType": "Offering Type",
    "supplierDetail.offeringProduct": "Product",
    "supplierDetail.offeringService": "Service",
    "supplierDetail.offeringBoth": "Products and Services",
    "supplierDetail.tags": "Tags",
    "supplierDetail.primaryContact": "Primary Contact",
    "supplierDetail.contactName": "Name",
    "supplierDetail.additionalInfo": "Additional Information",
    "supplierDetail.approvalStatus": "Approval Status",
    "supplierDetail.approved": "Approved",
    "supplierDetail.notApproved": "Not Approved",
    "supplierDetail.approvedDescription": "Supplier passed background check",
    "supplierDetail.notApprovedDescription": "Supplier pending approval",
    "supplierDetail.approvedAt": "Approved at",
    "supplierDetail.validUntil": "Valid until",
    "supplierDetail.quickActions": "Quick Actions",
    "supplierDetail.viewPOs": "View POs for this supplier",
    "supplierDetail.editSupplier": "Edit supplier",
    "supplierDetail.isApproved": "Supplier Approved",
    "supplierDetail.sizeMEI": "MEI - Individual Microentrepreneur",
    "supplierDetail.sizeME": "ME - Micro Enterprise",
    "supplierDetail.sizeEPP": "EPP - Small Business",
    "supplierDetail.sizeMedium": "Medium Enterprise",
    "supplierDetail.sizeLarge": "Large Enterprise",

    // Página de Novo Fornecedor
    "newSupplier.supplierData": "Supplier Data",
    "newSupplier.contact": "Contact",
    "newSupplier.attachments": "Attachments",

    // Barra Superior / Breadcrumbs
    "breadcrumb.purchaseOrders": "Purchase Orders",
    "breadcrumb.newPO": "New PO",
    "breadcrumb.approvals": "Approvals",
    "breadcrumb.legal": "Legal/Contracts",
    "breadcrumb.registrations": "Registrations",
    "breadcrumb.users": "Users",
    "breadcrumb.settings": "Settings",

    // Notificações
    "notification.poAwaitingApproval": "PO awaiting approval",
    "notification.poApproved": "PO approved",
    "notification.contractExpiring": "Contract expiring",
    "notification.requiresAnalysis": "requires your analysis",
    "notification.wasApproved": "was approved",
    "notification.expiresIn": "expires in",
    "notification.days": "days",
    "notification.viewAllNotifications": "View all notifications",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined
);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("pt");

  const t = (
    key: string,
    variables?: Record<string, string | number>
  ): string => {
    let translation = translations[language][key] || key;

    // Substituir variáveis no formato {{variableName}}
    if (variables) {
      Object.keys(variables).forEach((varKey) => {
        const placeholder = `{{${varKey}}}`;
        translation = translation.replace(
          new RegExp(placeholder, "g"),
          String(variables[varKey])
        );
      });
    }

    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

// eslint-disable-next-line react-refresh/only-export-components
export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
